### ISSUE TITLE
[Feature request] Closing brackets

### ISSUE THREAD

**Issue by KristerV** [zxqfl/tabnine-vscode#10]
For example. I write `elem` and it correctly suggests to me `elements.push(`. I just wish it also had the closing bracket (`elements.push()`). Without this I'm skeptical about if this thing actually saves time as I now need to think extra about what I'm seeing. Normal autocomplete is not as good at guessing, but at gives me what I expect.

**EDIT**

I've got a better example. 

1. I have `<button></button>`
2. I write `<button onC></button>`
3. it _very_ awesomly completes that to `<button onClick={() =></button>`
4. Now I must type `>}` just to close brackets. Result: `<button onClick={() => }></button>`

but notice how much brain power it takes to figure out what brackets are missing. This particual example is specially crazy as the `=>` symbol is very much what is expected so my brain goes "why did it remove the `>`? But actually the `>` belongs to the `<button>` tag already..

**EDIT2**

I just now noticed, that the caret is left at the end of the `=>` so `<button onClick={() =>|HERE|</button>`. Which confirms my (wrong) suspicion, that autocomplete added the `=>` and removed a `>`.

**Comment by nblackburn** [comment]
I imagine the reason it suggests `elements.push(` is because there is lots of suggestions starting with that but no context to derive which one you want, resulting in it falling back the the one with the most common ground until you provide it more context.

If you type something after `elements.push(`, i imagine it will start to become aware of your intent and will proceed to suggest things more along the lines of what you expect.

**Comment by zxqfl** [comment]
Fixed by TabNine 1.0.7 and subsequent client update.
